Move commit-specific methods from ZCL_ABAPGIT_BRANCH_OVERVIEW to new class ZCL_ABAPGIT_GIT_COMMIT
abapGit/abapGit pull request #4026
Opened 2020-10-15 08:37 UTC by mariusraht2

Related to #3040

It must be possible for e.g. feature #3040 to get commits from remote. We have already logic implemented that does exactly that in `ZCL_ABAPGIT_BRANCH_OVERVIEW`. Therefore I want to reuse it but the visibility and type of methods needed aren't allowing exactly that. Plus we should move those methods to object-specific classes instead of hiding them in classes only related to one specific overview UI/functionality.

**Change Log:**
- Create new class `ZCL_ABAPGIT_GIT_COMMIT`
- Move commit-specific methods from `ZCL_ABAPGIT_BRANCH_OVERVIEW` to `ZCL_ABAPGIT_GIT_COMMIT`
- Change methods visibility (from private to public) and type (from instance to class method)
- Added method `get_from_remote` that gets the commits from remote and sorts them by their hierarchy to eachother

2020-10-16 10:38 UTC, larshp commented on src/git/zcl_abapgit_git_commit.clas.abap
> +        !io_repo          TYPE REF TO zcl_abapgit_repo_online
Hi,
I'm trying to keep the repository concept outside of the `/git/` package, so it theoretically can be used for other things.
Suggest splitting this method into two, `get_by_branch` and `get_by_commit`, and then the URL and branch/sha1 can be passed

2020-10-16 11:27 UTC, mariusraht2 commented
@larshp Done :) Thanks for reviewing all my PRs with such patience 👍

2020-10-18 06:56 UTC, larshp requested changes

2020-10-18 06:56 UTC, larshp commented on src/git/zcl_abapgit_git_commit.clas.abap
> +        !iv_repo_name     TYPE string
seen with git eyes, a repository name does not exist, its an URL endpoint containing git objects

in the code, `iv_repo_name` is only used for a progress indicator, suggest using the URL for the progress indicator instead

2020-10-19 09:24 UTC, larshp approved these changes

2020-10-19 09:24 UTC, larshp commented
thanks 👍

2020-10-19 09:24 UTC, merged