Improve ""Cannot find .abapgit.xml" situation
abapGit/abapGit pull request #4240
Opened 2020-11-24 15:49 UTC by mbtools

Skip check during creating of repo and increase file count.

Closes #4174

2020-11-26 10:56 UTC, larshp requested changes
Comments below

2020-11-26 10:59 UTC, larshp commented
I dont think this should be a special case, it should be generic error handling from the create repo page.

1: User opens the repo page, enters data
2: Click create/clone

In my case the repository was created, but the UI stayed on the create repo page. If the repository is created, then the UI should show the repository, if not created then show error.

I have not looked into the details, but I guess there are more scenarios than the `.abapgit.xml` file issue

2020-11-26 16:02 UTC, mbtools commented
maybe this check should be a sep method that's called from the UI only

```abap
find_remote_dot_abapgit

    ELSEIF lines( mt_remote ) > c_new_repo_size.
      " Less files means it's a new repo (with just readme and license, for example) which is ok
      zcx_abapgit_exception=>raise( |Cannot find .abapgit.xml - Is this an abapGit repo?| ).
```

2020-11-27 09:34 UTC, larshp commented
hmm, yea, but still the repository is created when the exception occurs

I think,
a: move the error mentioned above, as it should just be a warning
b: there is something wrong with general error handling during creation and the UI flow, might be outside scope for this PR

2020-12-08 01:10 UTC, mbtools commented
- Removed exception during `new_online`
- Added warning to repo view
![image](https://user-images.githubusercontent.com/59966492/101423956-262c8a80-38c8-11eb-8add-2b57e1dd42b5.png)

2020-12-08 04:15 UTC, larshp requested changes

2020-12-08 04:15 UTC, larshp commented on src/zcl_abapgit_repo_content_list.clas.abap
> +  METHOD check_for_dot_abapgit.
suggest renaming this method to "check_repo_size" ?

2020-12-08 14:29 UTC, larshp approved these changes

2020-12-08 14:35 UTC, merged