new handler for SUSH
abapGit/abapGit pull request #4324
Opened 2020-12-14 09:29 UTC by d034973

object handler for SUSH was created

2020-12-14 09:33 UTC, larshp commented
thanks! 👍 

https://docs.abapgit.org/development/guidelines.html

abapGit targets 702 syntax so some of the statements needs downporting, plus also please pretty print with upper case keywords

2020-12-14 09:34 UTC, larshp commented
#1582

2020-12-14 09:48 UTC, larshp commented
https://github.com/abapGit-tests/SUSH created, please open a PR with a small SUSH example, so we have it for testing in the future

2020-12-14 11:28 UTC, larshp commented on src/objects/zcl_abapgit_object_sush.clas.abap
> +    IF cl_abapgit_factory=>get_environment( )->is_sap_cloud_platform( ). "[A4C_AGIT]
```suggestion
    IF cl_abapgit_factory=>get_environment( )->is_sap_cloud_platform( ) = abap_true. "[A4C_AGIT]
```

2020-12-14 11:55 UTC, larshp commented
due to the way abapGit is distributed, via copy-paste we cannot use text elements in the code

2020-12-14 14:01 UTC, mbtools commented
Unfortunately, the following objects do not in 702:
- `cl_su22_adt_object` 
- `if_su22_adt_object` 
- `cx_su2n_raise_events` 
- `cl_su22_appl`
- `cl_su2x`
- `cl_suso`

These will have to be replaced with generic objects, too. 

Replace the `CATCH cx_su2n_raise_events INTO lr_err.` with:

```abap
    CATCH cx_static_check INTO lr_err
        zcx_abapgit_exception=>raise( iv_text     = lx_err->get_text( )
                                      ix_previous = lx_err ).
```

2020-12-14 15:50 UTC, mbtools commented on src/objects/zcl_abapgit_object_sush.clas.abap
> +      CATCH cx_su2n_raise_events INTO lx_msg.
```abap
zcx_abapgit_exception=>raise( lx_msg->get_text( ) ).
```

2020-12-15 09:58 UTC, larshp commented
https://github.com/abapGit-tests/SUSH created, please open a PR with a small SUSH example, so we have it for testing in the future

2020-12-15 13:46 UTC, mbtools commented
Good work. It activates without errors on 702. Just two small changes (see above).

2020-12-15 13:46 UTC, mbtools requested changes

2020-12-15 13:46 UTC, mbtools commented on src/objects/zcl_abapgit_object_sush.clas.abap
> +    rv_user = c_user_unknown.
```abap
    DATA ls_key TYPE usobkey.

    ls_key = ms_item-obj_name.

    SELECT SINGLE modifier FROM usob_sm INTO rv_user
      WHERE name = ls_key-name AND type = ls_key-type.
    IF sy-subrc <> 0.
      rv_user = c_user_unknown.
    ENDIF.
```

2020-12-15 13:46 UTC, mbtools commented on src/objects/zcl_abapgit_object_sush.clas.xml
> +    <DESCRIPT>SAP-specific abapGIT object Handler for SUSH</DESCRIPT>
Change to `SUSH - Assignment: Service to Authorization Objects`

2020-12-15 14:20 UTC, mbtools approved these changes
Great. Thanks!

2020-12-15 14:21 UTC, mbtools commented
Just a small example for testing, please
https://github.com/abapGit-tests/SUSH

2020-12-15 15:37 UTC, d034973 commented
> Just a small example for testing, please
> https://github.com/abapGit-tests/SUSH

I sorry I just new here, I don't know where and how I have to describe an example for testing.

2020-12-15 16:13 UTC, mbtools commented
No problem. We will help :-) 

1. Go to https://github.com/abapGit-tests/SUSH and create a fork
2. In your system (where you have the new SUSH class), start abapGit and create a new online repo for the URL of your fork (should be https://github.com/d034973/SUSH). You can pick any local package like $SUSH. 
3. Add one SUSH object to this package (like ZAG_UNIT_TEST)
4. Go back to abapGit and you should see the new object in the list for the repo
5. Now stage everything and commit. 
6. The go to your forked repo and create a pull request (at the top there's a section showing the delta to the original and a compare button which you can click to create the PR)

2020-12-16 15:08 UTC, larshp commented
@d034973 did the above help? 

Marc also added it to https://docs.abapgit.org/development/serializers.html#testing

2020-12-16 15:13 UTC, d034973 commented
> @d034973 did the above help?
> 
> Marc also added it to https://docs.abapgit.org/development/serializers.html#testing

Hi guys, I am still on this topic. We have internal problem with our abapGit. The responsible colleagues are informed and I am waiting for update from this team. As soon our tool works fine, I will continue to create the tests

2020-12-28 12:23 UTC, larshp commented
I'll go ahead and merge this, feel free to open a new PR with additional changes. And add the SUSH test when possible, https://github.com/abapGit-tests/SUSH

welcome to abapGit as a contributor 🎉

2020-12-28 12:24 UTC, merged

2021-01-08 09:41 UTC, d034973 commented
@mbtools I have created the test for SUSH, could you please check it?