Docker infrastructure
abapGit/abapGit pull request #4445
Opened 2021-01-23 20:46 UTC by esjewett

This pull includes the barest minimum docker compose infrastructure that runs unit tests. There are a lot more improvements and adjustments that could be made, but this does all us to run `docker-compose run --workdir=\"/home/node/abapGit\" abapgit npm run-script unit` and execute the unit tests in the container.

What this will allow, aside from a more repeatable execution environment, is to provide local services to the container. For example, uncommenting lines 15-21 in docker-compose.yml allows us to `docker-compose run abapgit curl http://httpbin.com` and get the response "Hello World".

A few package.json scripts have been added for convenience:

- `docker-build` will build the necessary local Docker image, in this case from the `Dockerfile`. This is only needed if the `Dockerfile` or `docker-compose.yml` change, or the first time it is run.
- `docker-up` will bring up the Docker container. It is usually redundant as `docker-unit` will spawn its own containers as required.
- `docker-unit` will run the unit tests in the Docker container.
- `docker-down` will clean up the system.

One note: The container uses the local `node_modules` directory, so it is necessary to `npm install` prior to attempting to run tests through the Docker containers.

2021-01-24 07:45 UTC, larshp commented
can we move the 2 new files to a new folder `/test/` ?

2021-01-25 11:27 UTC, larshp requested changes
see comment above

2021-01-25 15:22 UTC, esjewett commented
@larshp Files moved and paths adjusted. Should all be working.

2021-01-25 17:26 UTC, larshp approved these changes

2021-01-25 17:26 UTC, merged