DEVC: Fix check if package is empty
abapGit/abapGit pull request #4466
Opened 2021-01-29 01:59 UTC by mbtools

SOTR object is linked to SAP package and removed together with the package on uninstall. Therefore, it should not be taken into account when checking if a package is empty.

2021-02-01 08:35 UTC, larshp commented
as far as I understand SOTR is a generic thing that is used for multiple objects? 

This change works only under the assumption that all SOTR objects are tied to the DEVC?

2021-02-01 14:28 UTC, mbtools commented
Exactly. If any other object - like a class - exists, `rv_is_empty` will be false. If there's only `DEVC` - with or without `SOTR` - left, then `rv_is_empty` should be true meaning the package can be deleted.

2021-02-01 14:35 UTC, larshp commented
but then the package contains a SOTR object, and I would expect it not to be possible to delete the package?

2021-02-01 18:48 UTC, larshp commented
oh, I think I read the code wrong, it doesnt skip any SOTR object

but only if the SOTR object belongs/is part of the DEVC

2021-02-01 18:50 UTC, larshp commented
I think the comment `SOTR is linked to SAP packages (DEVC)` can be misleading, SOTR is not linked to only DEVC on a general note

But if the SOTR is linked to the current DEVC, then it can be skipped

2021-02-02 16:42 UTC, larshp requested changes

2021-02-02 16:42 UTC, larshp commented on src/objects/zcl_abapgit_object_devc.clas.abap
> +    " SOTR is linked to SAP packages (DEVC)
```suggestion
    " Ignore the SOTR if is linked to the current SAP package (DEVC)
```

2021-02-02 20:00 UTC, larshp approved these changes

2021-02-02 20:01 UTC, merged