Replace GET_R3TR_OBJECT_FROM_LIMU_OBJ, fixes #4715
abapGit/abapGit pull request #4749
Opened 2021-05-05 09:44 UTC by vonglan

not tested in ABAPGit context, only locally.
First Pull Request, so please look closely.

2021-05-05 09:47 UTC, larshp commented
#4715

2021-05-05 11:08 UTC, mbtools requested changes
Thanks, Edo, for the fix. I tested your change and it works well in general. 

However, I discovered a bug that we should fix at this time. `rt_tadir` incorrectly contains objects that have been deleted already. For example:

![image](https://user-images.githubusercontent.com/59966492/117132237-d84a7e80-ada2-11eb-96e7-0d72f24f742a.png)


Could you please change the `append` as follows?

```abap
        IF ls_tadir-delflag IS INITIAL.
          APPEND ls_tadir TO rt_tadir.
        ENDIF.
```

2021-05-05 11:08 UTC, mbtools commented on src/cts/zcl_abapgit_transport.clas.abap
> +          IF 'TL' NS lv_result OR ls_tadir_sap IS INITIAL.
let's avoid yoda conditions

```abap
         IF lv_result NA 'TL' OR ls_tadir_sap IS INITIAL.
```

2021-05-06 16:01 UTC, vonglan commented on src/cts/zcl_abapgit_transport.clas.abap
> +          IF 'TL' NS lv_result OR ls_tadir_sap IS INITIAL.
done

2021-05-06 16:08 UTC, mbtools approved these changes

2021-05-06 16:09 UTC, mbtools commented
lgtm 👍

2021-05-09 08:53 UTC, larshp commented
welcome to abapGit as a contributor 🎉

2021-05-09 08:54 UTC, merged