Regenerate profile SAP_ALL
abapGit/abapGit pull request #4792
Opened 2021-05-25 16:16 UTC by juriadasek

Regenerate profile SAP_ALL after pulling some authorization object using abapgit. Please review, my first PR here :) 

Closes #4782

2021-05-25 16:22 UTC, mbtools requested changes
Small change to be compatible with 702 but good otherwise :-)

2021-05-25 16:22 UTC, mbtools commented on src/objects/zcl_abapgit_object_suso.clas.abap
> +
```abap
ls_e071-pgmid = 'R3TR'.
ls_e071-object = ms_item-obj_type.
ls_e071-obj_name = ms_item-obj_name.
INSERT ls_e071 INTO TABLE et_071.
```

2021-05-25 16:25 UTC, mbtools commented
Can you pls check if the delete method removes the AO from SAP_ALL. If not, add the regenerate there, too.

2021-05-26 07:32 UTC, juriadasek commented
@mbtools Do you know when this delete method is called? I couldn't find any 'delete' on UI. I just want to test it and make sure that everything is ok.

2021-05-26 09:39 UTC, mbtools commented
'Advanced > Uninstall' will call delete for each object of the repo

2021-05-26 10:49 UTC, jfilak commented
This method https://github.com/abapGit/abapGit/blob/85878b972a775918ddf674fef41143dc94d09ffa/src/objects/zcl_abapgit_object_suso.clas.abap#L182

2021-05-26 14:06 UTC, juriadasek commented on src/objects/zcl_abapgit_object_suso.clas.abap
> +
Fixed. I used that older syntax.

2021-05-26 19:17 UTC, jfilak commented
BTW: don't we need to update the changelong?

2021-05-27 03:21 UTC, flaiker commented
> BTW: don't we need to update the changelong?

Usually the changelog is updated for each release, not for every pull request.

2021-05-27 04:04 UTC, larshp commented
welcome to abapGit as a contributor 🎉

2021-05-27 04:05 UTC, merged