Dark mode for ENHO and SFPF to enable RFC pull
abapGit/abapGit pull request #4803
Opened 2021-05-30 10:30 UTC by filak-sap

I pull our repositories to newly created systems via RFC helpers and I had to prepare these to commits to make it working.

The commits have been deployed in all our systems for more then a month and I got not angry emails yet - so I bet those tens of users didn't run into any issue with them.

2021-05-31 19:34 UTC, mbtools requested changes
702 compatibility

2021-05-31 19:34 UTC, mbtools commented on src/objects/zcl_abapgit_object_sfpf.clas.abap
> +        lo_wb_form->delete( i_name = lv_name
see below

2021-05-31 19:34 UTC, mbtools commented on src/objects/zcl_abapgit_object_sfpf.clas.abap
> +          cl_fp_wb_form=>delete( i_name = lv_name
702

2021-05-31 19:34 UTC, mbtools commented on src/objects/zcl_abapgit_object_sfpf.clas.abap
> +                                              i_form = li_form
702

2021-05-31 19:35 UTC, mbtools commented
702: no dark_mode for sfpf

![image](https://user-images.githubusercontent.com/59966492/120234086-84bf3980-c257-11eb-9c77-ea4c4e4196bb.png)

![image](https://user-images.githubusercontent.com/59966492/120234105-90aafb80-c257-11eb-9d47-15922316c759.png)

2021-06-01 07:45 UTC, filak-sap commented
Alright, keep it as a down stream patch. Thank you!

2021-06-01 07:45 UTC, closed without merging

2021-06-01 07:55 UTC, mbtools commented
Don't close. It should be included . Just call the methods twice like this
https://github.com/abapGit/abapGit/blob/main/src/objects/zcl_abapgit_object_devc.clas.abap#L194