ENHO: Split code into separate files
abapGit/abapGit pull request #4951
Opened 2021-09-14 17:44 UTC by mbtools

Similar to class enhancements where enhanced methods are stored as individual files, this change separates the code for implicit enhancements (type `HOOK_IMPL`) into abap-files.

This makes the code more readable (instead of being embedded and escaped into XML) and allows for linting.

Note: The solution can still deserialize the old format but will serialize enhancements in the new format.

Old format:

![image](https://user-images.githubusercontent.com/59966492/133307056-e64476ee-93de-496e-96fa-50aae5668e84.png)

New format:

![image](https://user-images.githubusercontent.com/59966492/133307085-97fd2337-cfdb-45c5-ad07-a5505caed558.png)

![image](https://user-images.githubusercontent.com/59966492/133307095-5009362a-7c34-4b58-9948-38a26d08003e.png)

2021-09-14 17:46 UTC, mbtools commented
https://github.com/abapGit-tests/ENHO
main branch = old format
hook_impl branch = new format (merge to main after this PR is merged)

2021-09-18 04:26 UTC, larshp requested changes
What is the stability of the files?

Ie. if the 0001 hook is removed from the list of enhancements?

maybe make the filenames a hash of FULL_NAME?

2021-09-22 03:54 UTC, larshp commented
A: Suggest keeping the source ABAP code as is, let the developer decide what goes into it. Currently, if the developer removes the top comment, deserialization will break without an error?

B: Instead of re-using the SOURCE field, suggest adding a new field for the file name
```
<SOURCE>
  <item>FILE:2b2cade4</item>
</SOURCE>
```
eg
```
<SOURCE_FILE>FILE:2b2cade4</SOURCE>
```
I think it will be easier to parse, and determine if its using the old or new format

2021-09-22 14:31 UTC, mbtools commented
I can't use a new field since it's a standard structure. I put the file names into a separate block.

The comment for the full name is helpful if you just browse the code online, for example. I changed the deserialize so it takes only the code between the enhancement statements and ignores the rest.

2021-09-23 05:51 UTC, larshp approved these changes

2021-09-24 04:34 UTC, merged