WDCC:Support all Config Types
abapGit/abapGit pull request #4985
Opened 2021-09-29 11:14 UTC by Lutzi3

Before only config type 00 (general) was supported. Now all types are allowed. This enables ABAPGit for instance to transport (cross client) Fiori Catalogs and Groups !

2021-09-29 13:25 UTC, mbtools requested changes
Thanks for the improvement. I looked at `TADIR` and there are cases where `obj_name` includes the third part of the key. We should add it to be complete.

2021-09-29 13:25 UTC, mbtools commented on src/objects/zcl_abapgit_object_wdcc.clas.abap
> +    ls_config_key-config_type = ms_item-obj_name+32(2).
ls_config_key-config_var = ms_item-obj_name+34(6).

2021-09-29 13:25 UTC, mbtools commented on src/objects/zcl_abapgit_object_wdcc.clas.abap
> +    ls_config_key-config_type = ms_item-obj_name+32(2).
ls_config_key-config_var = ms_item-obj_name+34(6).

2021-09-29 13:25 UTC, mbtools commented on src/objects/zcl_abapgit_object_wdcc.clas.abap
> +    ls_config_key-config_type = ms_item-obj_name+32(2).
ls_config_key-config_var = ms_item-obj_name+34(6).

2021-09-29 13:25 UTC, mbtools commented on src/objects/zcl_abapgit_object_wdcc.clas.abap
> +    ls_config_key-config_type = ms_item-obj_name+32(2).
ls_config_key-config_var = ms_item-obj_name+34(6).

2021-09-29 13:26 UTC, mbtools commented
Example:

![image](https://user-images.githubusercontent.com/59966492/135277502-1283f258-1b41-40ee-a880-4408fe4013e5.png)

2021-09-29 14:39 UTC, Lutzi3 commented on src/objects/zcl_abapgit_object_wdcc.clas.abap
> +    ls_config_key-config_type = ms_item-obj_name+32(2).
was added

2021-09-29 14:39 UTC, Lutzi3 commented on src/objects/zcl_abapgit_object_wdcc.clas.abap
> +    ls_config_key-config_type = ms_item-obj_name+32(2).
was added

2021-09-29 14:39 UTC, Lutzi3 commented on src/objects/zcl_abapgit_object_wdcc.clas.abap
> +    ls_config_key-config_type = ms_item-obj_name+32(2).
was added

2021-09-29 17:45 UTC, mbtools approved these changes

2021-09-29 17:50 UTC, mbtools commented
Closes #4972

Could you please create a small test case for 07 and add it to https://github.com/abapGit-tests/WDCC_Fiori?

2021-09-30 15:32 UTC, Lutzi3 commented
> Closes #4972
> 
> Could you please create a small test case for 07 and add it to https://github.com/abapGit-tests/WDCC_Fiori?

This was done. I created another Pull request for this repo.

2021-10-01 06:12 UTC, larshp commented
welcome to abapGit as a contributor 🎉

2021-10-01 06:14 UTC, merged

2021-10-03 08:14 UTC, Lutzi3 commented
> welcome to abapGit as a contributor 🎉

It is my pleasure ! 
In the context of Custom Code Migration (I am development architect and specialised on this topic) I use ABAPGit very often for transfers or archivings.
Kind Regards
Lutz