AIFC additional interface validation checks
abapGit/abapGit pull request #5267
Opened 2022-01-11 08:45 UTC by D047539

Additional validation checks are required when AIFC content is downloaded from abapGIT before anything is written to DB / persisted.
See Issue #5250

2022-01-11 08:53 UTC, larshp commented
@D047539 check conflicts

2022-01-11 09:51 UTC, D047539 commented
> @D047539 check conflicts

remove AIF types

2022-01-11 10:00 UTC, larshp commented
you should see this button,
![image](https://user-images.githubusercontent.com/5888506/148921647-cb1e5310-76a5-48bc-8ea6-2788d63fd197.png)

2022-01-11 12:08 UTC, mbtools requested changes

2022-01-11 12:08 UTC, mbtools commented on src/objects/zcl_abapgit_object_aifc.clas.abap
> +        IF execute_checks( io_xml = io_xml ) = abap_false.
if there's just one parameter, please remove the parameter name: execute_checks( io_xml ). There're are few occurances like this. Thanks

2022-01-14 09:22 UTC, D047539 commented
Note 3117150 (https://launchpad.support.sap.com/#/notes/3117150) needs to be implemented (re-implemented)

2022-01-14 09:33 UTC, christianguenter2 commented
> Note 3117150 (https://launchpad.support.sap.com/#/notes/3117150) needs to be implemented (re-implemented)

Cannot implement note on 755 SP01. Whereas with previous version of the note it was possible.
![grafik](https://user-images.githubusercontent.com/17437789/149492716-c878e629-dc0a-4861-898a-8bf1069d7cc6.png)

2022-01-14 09:55 UTC, D047539 commented
> @D047539
> 
> > Note 3117150 (https://launchpad.support.sap.com/#/notes/3117150) needs to be implemented (re-implemented)
> 
> Cannot implement note on 755 SP01. Whereas with previous version of the note it was possible. ![grafik](https://user-images.githubusercontent.com/17437789/149492716-c878e629-dc0a-4861-898a-8bf1069d7cc6.png)

I just released the note. It may take some time before the note is fully updated.

2022-01-15 10:07 UTC, christianguenter2 commented
@D047539 
I was able to implement the note. Is there a way to delete AIFC objects?

2022-01-15 10:13 UTC, christianguenter2 commented on src/objects/zcl_abapgit_object_aifc.clas.abap
> +        ENDIF.
Maybe simplify this and other places to
```suggestion
        IF sy-subrc = 0.
          ls_ifkeys-ns = <lv_value>.
        ENDIF.
```

2022-01-15 10:13 UTC, christianguenter2 commented on src/objects/zcl_abapgit_object_aifc.clas.abap
> +    CLEAR lr_tabledescr.
No need to clear local variable
```suggestion
```

2022-01-15 10:15 UTC, christianguenter2 commented on src/objects/zcl_abapgit_object_aifc.clas.abap
> +        READ TABLE <lt_table> ASSIGNING <ls_table> INDEX 1.
What if `READ` fails? If it never should fail I'd suggest to add `ASSERT sy-subrc = 0`

2022-01-17 07:47 UTC, D047539 commented
> @D047539 I was able to implement the note. Is there a way to delete AIFC objects?

Currently it is not possible to delete AIFC objects

2022-01-17 09:13 UTC, christianguenter2 commented
> > @D047539 I was able to implement the note. Is there a way to delete AIFC objects?
> 
> Currently it is not possible to delete AIFC objects

Hm, ok. Then I can't test.

2022-01-17 09:23 UTC, larshp commented
well, if thats how AIFC works, @D047539 I guess its a limitation in the tooling? Is it described somewhere on help.sap.com?

2022-01-17 10:11 UTC, mbtools commented
no delete = no unit tests, no ci tests. not sure if we want to introduce objects like this to abapGit. 

if there's no proper api, there's also batch input.

2022-01-17 13:39 UTC, mbtools approved these changes
The code looks ok but I have no way of testing it. Nicole, the missing delete feature is _not_ a show stopper but it's fairly limiting how useful abapGit will be for `AIFC`. If and when SAP adds deletion, please add it to abapGit as well via PR.

2022-01-18 09:38 UTC, merged