DDIC: Improve active/inactive check
abapGit/abapGit pull request #5486
Opened 2022-04-25 15:57 UTC by mbtools

Use `is_active_ddic` (function `DDIF_STATE_GET`) for all DDIC object types (in addition to `TABL`). 

This is more accurate than the current method (function `RS_INACTIVE_OBJECTS_WARNING`) since it detects newly created but not active objects as well. Newly created DDIC objects will be shown in the repo view with an "inactive" icon instead of appearing as non-existing. 

Before: Error msg

![image](https://user-images.githubusercontent.com/59966492/165127078-3054fc24-6429-42ba-ad67-a8307c549169.png)

After: Object is shown with inactive status

![image](https://user-images.githubusercontent.com/59966492/165127102-7af0eb4c-8969-4572-95d8-2c49a92e3fc8.png)

2022-05-07 07:04 UTC, larshp requested changes
see comment above

2022-05-07 08:18 UTC, mbtools commented on src/objects/zcl_abapgit_objects_super.clas.abap
> +        state         = 'M'
WIth 'A' you only get 'A' or '' as `gotstate` (active or not). With 'M' you also get the other possible states. The function is actually documented by SAP ;-)

2022-05-07 09:23 UTC, larshp commented on src/objects/zcl_abapgit_objects_super.clas.abap
> +        state         = 'M'
suggest adding a comment in the code? I dont think its obvious that M is the correct value here

2022-05-07 10:06 UTC, mbtools commented on src/objects/zcl_abapgit_objects_super.clas.abap
> +        state         = 'M'
updated comment

2022-05-09 06:07 UTC, larshp approved these changes

2022-05-09 06:08 UTC, merged