[AFF] Object handler for INTF
abapGit/abapGit pull request #5660
Opened 2022-06-27 08:16 UTC by albertmink

see #5658

2022-06-28 09:38 UTC, albertmink commented
Result of the serialization (left), after being deserialized into the ABAP system. Reference AFF file on the right.
![image](https://user-images.githubusercontent.com/38354196/176146541-8642fd01-751d-463a-83bd-c3bed4c83d9f.png)

Example repo https://github.com/albertmink/testing_intf_aff

2022-06-28 10:07 UTC, larshp commented on src/objects/zcl_abapgit_object_intf.clas.abap
> +        iv_package TYPE devclass
no need to fix these unrelated lines, someone opening the code in SE80 will revert it

2022-06-28 10:13 UTC, larshp requested changes
on a general note, looking a this, we need to define what the internal representation of the object is, abstract it, and have two different ways for reading data into that representation

2022-06-28 12:07 UTC, albertmink commented
will pause here and the refactoring first. First fill the ABAP data type, then put it to XML/JSON(experimental flag)

2022-06-30 12:52 UTC, albertmink commented on src/objects/zcl_abapgit_object_intf.clas.abap
> +                              clif_name = is_interface_key-clsname ).
indeed, its been removed in this PR.

2022-06-30 13:06 UTC, larshp commented on src/objects/zcl_abapgit_object_intf.clas.abap
> +      ENDTRY.
put all this into the local class? a static method is okay from my POV

as things evolve, we might need to change this part, putting it to the local class reduces that impact

2022-06-30 13:07 UTC, larshp commented on src/objects/zcl_abapgit_object_intf.clas.abap
> +      ENDTRY.
put all this into the local class? a static method is okay from my POV

as things evolve, we might need to change this part, putting it to the local class reduces that impact

2022-06-30 13:34 UTC, larshp commented on src/objects/zcl_abapgit_object_intf.clas.abap
> +      lx_exception        TYPE REF TO cx_root,
```suggestion
```

2022-06-30 13:47 UTC, larshp approved these changes

2022-06-30 14:06 UTC, merged