new SOBJ serializer
abapGit/abapGit pull request #5724
Opened 2022-08-19 10:48 UTC by rayatus

new SOBJ serializer relying on GENERIC serializer

2022-08-19 12:06 UTC, larshp commented on src/objects/zcl_abapgit_object_sobj.clas.abap
> +    SELECT SINGLE crea_user, chan_user INTO @DATA(ls_userinfo) FROM tojtb WHERE name = @ms_item-obj_name.
downport to 702,

```suggestion
    SELECT SINGLE crea_user, chan_user INTO ls_userinfo FROM tojtb WHERE name = ms_item-obj_name.
```

2022-08-19 15:06 UTC, mbtools commented
nice. please add a test object to https://github.com/abapGit-tests/SOBJ

2022-08-19 15:13 UTC, rayatus commented
> nice. please add a test object to https://github.com/abapGit-tests/SOBJ

@mbtools there is [PR ](https://github.com/abapGit-tests/SOBJ/pull/1) waiting for it

2022-08-19 17:06 UTC, mbtools commented
thanks. i will test it next week

2022-08-31 15:02 UTC, rayatus commented
@mbtools , just wondering if you had the time to have a look at this PR.
Let me know if I could help someway or if there is anything pending from my side. ;)

2022-09-02 21:02 UTC, mbtools requested changes
Sorry for the delay. Tests with the example repo worked fine. Just a couple small changes

2022-09-02 21:02 UTC, mbtools commented on src/objects/zcl_abapgit_object_sobj.clas.abap
> +*    ri_rules->add(
remove commented code

2022-09-02 21:02 UTC, mbtools commented on src/objects/zcl_abapgit_object_sobj.clas.xml
> +    <DESCRIPT>SOBJ - Business Object</DESCRIPT>
change the description to "SOBJ - Business Object Type"

2022-09-05 16:28 UTC, mbtools approved these changes
👍

2022-09-05 16:58 UTC, merged