Enhance User Exit Framework
abapGit/abapGit pull request #6307
Opened 2023-05-28 17:21 UTC by mbtools

Currently, we are limited to one class (`zcl_abapgit_user_exits`) for implementing all exist methods. This leads to conflicts or manual effort when several solutions need to implement exits.

Note: There's a lot of text (documentation) below but the solution is actually quite simple. 

### Goals of this Enhancement

- Compatibility: existing user exits continue to work as is
- Development: new framework is easy to implement and maintain
- Deployment: repos are able to ship user exit implementations
- Runtime: support for more than one exit class within one or more repos
- Migration: low effort to move existing user exit implementations to the new framework

### Solution

1. Class `zcl_abapgit_exit_super` 

- Contains a default implementation for all exit methods (i.e. just a `RETURN` statement)
- Is used as super class for classes implementing exists
- Therefore, a class for user exists just needs to redefined the methods it wants to implement
- Changes to unused methods and addition of new methods will not impact your exit class anymore

2. Class `zcl_abapgit_exit_caller`

- Collects all sub-classes of `zcl_abapgit_exit_super` 
- Is used as a super-class for `zcl_abapgit_user_exit` (see below)
- For each exit method, `zcl_abapgit_exit_caller` calls the corresponding method in the sub-classes collected above (obviously, only redefined methods will have any effect)
- For most methods, all sub-classes will be called (cumulative effect)
- For some methods, the first successful call will win (exclusive effect)

### Limitation

Currently, the solution only works for the developer version. The standalone continues to work with the existing include `zabapgit_user_exit`. 

Note: I'm still investigating if and how this framework can work also for the standalone version.

### Downside

When adding new exit methods, we have to maintain two additional classes:

- `zif/cl_abapgit_exit`: same as before
- `zcl_abapgit_exit_super`: add `RETURN` to new method implementation
- `zcl_abapgit_exit_called`: implement a `LOOP` over all exit sub-classes

However, the additional effort is very low and only once per exit method.

### Example

The implementation of `zcl_abapgit_user_exit` is reduced to the following (no method code):

```abap
CLASS zcl_abapgit_user_exit DEFINITION
  PUBLIC
  INHERITING FROM zcl_abapgit_exit_caller
  CREATE PUBLIC.

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.

CLASS zcl_abapgit_user_exit IMPLEMENTATION.
ENDCLASS.
```

Here's an exit class for creating the HTTP client based on an RFC connection:

```abap
CLASS zcl_abapgit_user_exit_client DEFINITION
  PUBLIC
  INHERITING FROM zcl_abapgit_exit_super
  CREATE PUBLIC.

  PUBLIC SECTION.

    METHODS zif_abapgit_exit~create_http_client REDEFINITION.

  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.

CLASS zcl_abapgit_user_exit_client IMPLEMENTATION.

  METHOD zif_abapgit_exit~create_http_client.

    DATA:
      lv_host        TYPE string,
      lv_destination TYPE rfcdest.

    lv_host = zcl_abapgit_url=>host( iv_url ).

    IF lv_host CS 'github'.
      lv_destination = 'GITHUB'.
    ELSE.
      RETURN.
    ENDIF.

    cl_http_client=>create_by_destination(
      EXPORTING
        destination              = lv_destination
      IMPORTING
        client                   = ri_client
      EXCEPTIONS
        argument_not_found       = 1
        destination_not_found    = 2
        destination_no_authority = 3
        plugin_not_active        = 4
        internal_error           = 5
        OTHERS                   = 6 ).

    IF sy-subrc <> 0.
      zcx_abapgit_exception=>raise_t100(  ).
    ENDIF.

    zcl_abapgit_login_manager=>clear( ).

  ENDMETHOD.
ENDCLASS.
```

The implementation becomes a lot simpler and more robust. Plus you can have any number of such exit sub-classes. Repositories can include sub exit sub-classes.

### Migration

You can easily transition from an existing `zcl_abapgit_user_exit` implementation to several classes:

1. Create one or more exit classes each with `zcl_abapgit_exit_super` as superclass
2. Redefine only methods as required and copy corresponding code from `zcl_abapgit_user_exit`
3. Once all methods are migrated to sub-classes, replace `zcl_abapgit_user_exit` as shown in the example above

### Practical Experience

I have distributed methods across six exit classes and four repos and it works perfectly well. 🎉 

Closes #4786

2023-05-28 18:25 UTC, larshp requested changes
if there are two classes, one piece of logic must be executed before the other or vice versa, I dont think it can be handled?

- like one adds to tadir results, one modifying tadir, the add must be done first
- like deciding the proxy port, one exit says 8080, a different says 8081
- one says wall message must be A, one says wall message must be B

the users must decide the exits and maintain those, shipping an exit is "add call to shipped=>logic() in user exit something"

2023-05-28 19:13 UTC, mbtools commented
Certainly depends on the exit method. In some cases, having multiple classes won't make much sense (like for changing the proxy). But why would someone implement these methods multiple times? 

If the order matters, you can redefine the method inherited from `zcl_abapgit_exit_caller`. You could use another order, or call only selected exit classes. Up to the user. 

I have three different wall messages. Each is adding a bit of HTML. No problem.

2023-05-29 05:51 UTC, larshp commented
> But why would someone implement these methods multiple times?

thats my point, no-one would. But pulling 4 different exit classes, the developer will not easily know what is implemented and how/if they overlap or ordering matters

Alternative solutions:
* do one interface per method, allows shipping
* go full BADI, then its possible to get an overview and a familiar setup

2023-05-29 07:15 UTC, mbtools commented
We don't have to ship it with AG. I will put it in a separate repo.

2023-05-29 07:15 UTC, closed without merging