Introduce ABAP Language Version base functionality
abapGit/abapGit pull request #6346
Opened 2023-07-13 09:58 UTC by ThomasPloski

2023-07-13 10:21 UTC, larshp commented on src/repo/zcl_abapgit_repo.clas.abap
> +    IF NEW zcl_abapgit_abap_language_vers( )->is_import_allowed( io_repo = me iv_package = ms_data-package ) = abap_false.
this is not valid 702 syntax

2023-07-13 12:26 UTC, ThomasPloski commented on src/repo/zcl_abapgit_repo.clas.abap
> +    IF NEW zcl_abapgit_abap_language_vers( )->is_import_allowed( io_repo = me iv_package = ms_data-package ) = abap_false.
resolved

2023-07-13 16:36 UTC, mbtools commented
The types and constants are already included in 
https://github.com/abapGit/abapGit/blob/main/src/objects/aff_types/zif_abapgit_aff_types_v1.intf.abap 
(which is a copy of https://github.com/SAP/abap-file-formats/blob/main/file-formats/zif_aff_types_v1.intf.abap).

This adds them in `zif_abapgit_definitions` and `zcl_abapgit_abap_language_vers`. Can we keep them in one place?

2023-07-14 09:30 UTC, schneidermic0 reviewed
See my comments

2023-07-14 09:30 UTC, schneidermic0 commented on src/utils/zcl_abapgit_abap_language_vers.clas.abap
> +        rv_allowed_abap_langu_version =  c_allowed_abap_langu_version-standard.
I guess, here we have to differentiate between source code object and non-source code objects, don't we?

2023-07-19 07:59 UTC, ThomasPloski commented
> zif_abapgit_definitions



> The types and constants are already included in https://github.com/abapGit/abapGit/blob/main/src/objects/aff_types/zif_abapgit_aff_types_v1.intf.abap (which is a copy of https://github.com/SAP/abap-file-formats/blob/main/file-formats/zif_aff_types_v1.intf.abap).
> 
> This adds them in `zif_abapgit_definitions` and `zcl_abapgit_abap_language_vers`. Can we keep them in one place?

I have reused the already defined constants in zif_abapgit_aff_types_v1=>ty_abap_language_version.
Since the introduced ABAP Language Version in .abapgit.xml contains of semantically readable values like standard, keyUser, cloudDevelopment), I have decided to let the definition in the zif_abapgit_dot_abapgit interface.

2023-07-20 08:49 UTC, schneidermic0 commented on src/utils/zcl_abapgit_abap_language_vers.clas.abap
> +        rv_allowed_abap_langu_version =  c_allowed_abap_langu_version-standard.
@ThomasPloski and I discussed this. We try put the logic to the object handlers that need a "special" standard ABAP language version. If this won't work out, we add this logic later

2023-07-20 08:50 UTC, schneidermic0 approved these changes
Changes look good to me, now.

2023-07-20 14:16 UTC, larshp commented
heh, so the changes from main combined with the changes in this PR gives a linter error, both changes independent no error 😄 dont think I've seen this before, but yea, possible

2023-07-20 22:17 UTC, mbtools requested changes
Some minor changes. The deserialize method became too long. We will refactor in separate PR later. Just set the check to 110 in your PR.

https://github.com/abapGit/abapGit/blob/9075658c3f0998ee859b6c319950179c9a8564c3/abaplint.json#L354

2023-07-20 22:17 UTC, mbtools commented on src/objects/zcl_abapgit_objects.clas.abap
> +            <ls_deser>-item-abap_language_version = lo_abap_language_vers->get_abap_language_vers_by_objt(
Let's move this assigment up to right after `ls_item-devclass = lv_package.` (line 108). This way ALaV will be passed properly to the constructor via `create_object`.

2023-07-20 22:17 UTC, mbtools commented on src/utils/zcl_abapgit_abap_language_vers.clas.abap
> +        !io_repo                             TYPE REF TO zif_abapgit_repo
remove unused parameter `io_repo`

2023-07-20 22:17 UTC, mbtools commented on src/utils/zcl_abapgit_abap_language_vers.clas.abap
> +        RETURN.
remove all 'RETURN`s

2023-07-21 06:47 UTC, larshp commented on src/objects/zcl_abapgit_objects.clas.abap
> +                                                                                                 iv_package = lv_package ).
```suggestion
          ls_item-abap_language_version = lo_abap_language_vers->get_abap_language_vers_by_objt( 
            iv_object_type = ls_item-obj_type
            iv_package = lv_package ).
```

2023-07-22 22:29 UTC, mbtools commented
I tested it on 702 with https://github.com/abapGit-tests/DDIC_integration (which contains core object types like `clas` `prog`, `fugr` as well). Works as usual. 

good to merge from my pov

2023-07-23 09:11 UTC, larshp commented
@mbtools dismiss or approve your review?

2023-07-23 12:26 UTC, mbtools approved these changes

2023-07-23 13:03 UTC, merged