put zcl_abapgit_default_transport behind interface
abapGit/abapGit pull request #6673
Opened 2023-11-28 18:02 UTC by larshp

2023-11-28 19:21 UTC, mbtools requested changes
small change for `sod1/2`

2023-11-28 19:21 UTC, mbtools commented on src/objects/zcl_abapgit_object_sod1.clas.abap
> +        lv_transport_request = zcl_abapgit_factory=>get_default_transport( )->get( )-ordernum.
this should actually use `iv_transport`

2023-11-28 19:21 UTC, mbtools commented on src/objects/zcl_abapgit_object_sod2.clas.abap
> +        lv_transport_request = zcl_abapgit_factory=>get_default_transport( )->get( )-ordernum.
`iv_transport`

2023-11-28 19:25 UTC, mbtools commented
co-pilot loves some detail 😀

2023-11-29 06:08 UTC, larshp commented
> co-pilot loves some detail 😀

yea, its not super useful IMHO

2023-11-29 06:11 UTC, larshp commented on src/objects/zcl_abapgit_object_sod1.clas.abap
> +        lv_transport_request = zcl_abapgit_factory=>get_default_transport( )->get( )-ordernum.
fixed

2023-11-29 06:11 UTC, larshp commented on src/objects/zcl_abapgit_object_sod2.clas.abap
> +        lv_transport_request = zcl_abapgit_factory=>get_default_transport( )->get( )-ordernum.
fixed

2023-11-29 19:51 UTC, mbtools approved these changes
👍

2023-11-30 06:48 UTC, merged