Fix Unexpected Functionality for "Maximum Length of Comment" Field"
abapGit/abapGit pull request #6871
Opened 2024-03-20 04:38 UTC by francisco-milan

This PR fixes the issue documented in #

2024-03-20 22:18 UTC, mbtools requested changes
50 is the recommended max for the title (https://www.git-scm.com/docs/git-commit#_discussion) so that is the default value for the setting.

Users should be able to pick other values. min = 1 is correct, but max should be limited to what fits into a single line. That's about 100 characters. Maybe someone likes higher values and has them already set in abapGit. Let's set max = 250. 

Example where the commit title "should fit":

![image](https://github.com/abapGit/abapGit/assets/59966492/25f06e97-defa-4841-a3a2-c0b7e4830e76)

2024-03-20 22:18 UTC, mbtools commented on src/ui/lib/zcl_abapgit_html_form_utils.clas.abap
> +      lv_number TYPE int8.
won't work in 702

2024-03-21 02:37 UTC, francisco-milan commented
Test results after implementing the requested changes:

**Scenario 1**. "Maximum Length of Comment" set to a value <= -10,000,000,000,000,000,000,000,000,000,000 (32 digits or more).
Here I'm proposing to change the original error message, so instead of "Maximum Length of Comment is not numeric" we can display something like: "Input Value Out of Range. Please enter a numeric value with less than 32 digits". 

![image](https://github.com/abapGit/abapGit/assets/36721657/e81bbdc3-afcb-4ca9-8dbd-fc68c1dfc463)

**Scenario 2**. "Maximum Length of Comment" set to a value >= -9,999,999,999,999,999,999,999,999,999,999 AND < 1 (up to 31 digits).

![image](https://github.com/abapGit/abapGit/assets/36721657/2a148ea5-47d0-4665-a57f-81ccda139e69)

**Scenario 3**. "Maximum Length of Comment" set to a value >= 1 AND <= 250.

![image](https://github.com/abapGit/abapGit/assets/36721657/a70cf2ef-3662-4ebb-93ec-ed6d9a59b6cd)

**Scenario 4**. "Maximum Length of Comment" set to a value >= 251 AND <= 9,999,999,999,999,999,999,999,999,999,999 (up to 31 digits).

![image](https://github.com/abapGit/abapGit/assets/36721657/371a637d-f0c0-4219-93f6-88a8444fd1b0)

**Scenario 5**. "Maximum Length of Comment" set to a value >= 10,000,000,000,000,000,000,000,000,000,000 (32 digits or more). Also here I would like to use the revised version of the error message instead of the original ("Maximum Length of Comment is not numeric").

![image](https://github.com/abapGit/abapGit/assets/36721657/aeceeff3-6d54-4349-af82-9f55d1db51d2)

If you have any questions or comments, please let me know.

Best regards,

Francisco Milan.

2024-03-21 02:39 UTC, francisco-milan commented
Closes #6872

2024-03-21 10:56 UTC, mbtools approved these changes
👍

2024-03-21 11:01 UTC, mbtools approved these changes
👍

2024-03-21 11:06 UTC, merged