UIPG, UIST: Add support for Launchpad Page and Space Templates
abapGit/abapGit pull request #6873
Opened 2024-03-20 15:51 UTC by ViktoriaFreidel

Register new SAP Object in abapGit

2024-03-20 15:54 UTC, larshp commented
make sure to downport to 702 syntax, and if objects doesnt exist on 702 change it to dynamic calls

2024-03-20 18:32 UTC, mbtools requested changes
We know it's a pain but abapGit supports 702 and higher so you can't use 740 language features. Objects that don't exist must be coded dynamically. Best to look at some other classes on how it's done there.

2024-03-20 18:32 UTC, mbtools commented on src/objects/aff/zcl_abapgit_object_uipg.clas.abap
> +        DATA(lo_api) = NEW /ui2/cl_uist_sval_sql( ).
Code must run on 702

Create object...

2024-03-20 18:32 UTC, mbtools commented on src/objects/aff/zcl_abapgit_object_uipg.clas.abap
> +        DATA(ls_metadata) = /ui2/cl_uipg_db_access=>get_instance( )->read_wb_metadata( iv_page_id  = CONV #( ms_item-obj_name )
- No CONV (740)
- class must be called dynamically since it doesn't exist in 702

2024-03-20 18:32 UTC, mbtools commented on src/objects/aff/zcl_abapgit_object_uipg.clas.abap
> +      CATCH /ui2/cx_uipg INTO DATA(lx_error).
Replace with cx_root

2024-03-20 21:38 UTC, mbtools reviewed
two shortcuts but looks good otherwise

2024-03-20 21:38 UTC, mbtools commented on src/objects/aff/zcl_abapgit_object_uipg.clas.abap
> +        zcx_abapgit_exception=>raise( iv_text     = lx_root->get_text( )
`zcx_abapgit_exception=>raise_with_text( lx_root ).`

2024-03-20 21:38 UTC, mbtools commented on src/objects/aff/zcl_abapgit_object_uist.clas.abap
> +        zcx_abapgit_exception=>raise( iv_text     = lx_root->get_text( )
`zcx_abapgit_exception=>raise_with_text( lx_root ).`

2024-03-20 21:50 UTC, ViktoriaFreidel commented on src/objects/aff/zcl_abapgit_object_uipg.clas.abap
> +        zcx_abapgit_exception=>raise( iv_text     = lx_root->get_text( )
Thanks, make sense

2024-03-20 22:06 UTC, mbtools commented
something went wrong. there's duplicate code in the change-by methods.

2024-03-20 22:25 UTC, ViktoriaFreidel commented
Sorry, I damage the code. :-( . The merge of conflicts did what I don't wanted. I will send a fix.

2024-03-20 23:04 UTC, mbtools commented
The language is set in the constructor. I replaced sy-langu accordingly.

2024-03-20 23:04 UTC, mbtools approved these changes
👍

2024-03-20 23:05 UTC, mbtools commented
Please create minimal test cases in https://github.com/abapGit-tests/UIPG and https://github.com/abapGit-tests/UIST. Thanks!

2024-03-21 08:56 UTC, ViktoriaFreidel commented
Hi, I try to add a simple test in https://github.com/abapGit-tests/UIST. How can I merge pull request https://github.com/abapGit-tests/UIST/pull/1.  It is about missing write access. 
Could you help to set a correct rights to be able add a test in those repositories? 
BR, Viktoria

2024-03-21 09:42 UTC, larshp commented
does these object types have entries in TADIR?

2024-03-21 10:01 UTC, ViktoriaFreidel commented
Yes,  both object types have entries in TADIR 
PGMID         R3TR
OBJECT        UIST or UIPG
OBJ NAME   <Space or Page Id>

2024-03-21 10:54 UTC, mbtools approved these changes
LGTM 👍

2024-03-21 10:57 UTC, larshp commented
welcome to abapGit as a contributor 🎉

2024-03-21 10:57 UTC, merged