Refactor: i18n filename logic
abapGit/abapGit pull request #6892
Opened 2024-04-02 15:14 UTC by mbtools

Closes #6865

Move the logic for `i18n` files to `zcl_abapgit_filename_logic`. 

@albertmink could you please do a quick test that the interface translation logic still works properly after this change?

PS: As a follow-up step, I will replace `zcl_abapgit_objects_files=>get_i18n_properties_file` with `read_i18n_files` so that `po` and `properties` files are handled the same way.

2024-04-02 17:26 UTC, albertmink commented
Will test later this week

2024-04-04 08:24 UTC, albertmink requested changes
Thanks, I could pull/change/push the properties files.

There is some copy/paste from `po` logic that is not needed, as a lot of the logic is pushed to the objects itself.  Maybe later in development this is needed.

Overall it is very hard to read the diffs (maybe I shouldn't review the lines, but the functionality). Methods that are moved around and hence, not shown properly in the diffs.

2024-04-04 08:24 UTC, albertmink commented on src/objects/texts/zcl_abapgit_properties_file.clas.abap
> +    METHODS parse
AFAIK: `parse` is not used as logic is pushed down to CLAS object_intf

2024-04-04 08:24 UTC, albertmink commented on src/objects/core/zcl_abapgit_objects_files.clas.abap
> +        WHEN 'properties'.
See other comment
<img width="605" alt="Screenshot 2024-04-04 at 10 12 36" src="https://github.com/abapGit/abapGit/assets/38354196/e391cc6f-7bc3-489d-a3c1-28e1c4515d81">

2024-04-04 14:40 UTC, mbtools commented
I was interested in the functional test, just to confirm that I didn't mess anything up.

The next PR should then move the json-path logic to the `parse` method of `zcl_abapgit_properties_file` so you don't have to repeat it for every object type.

2024-04-04 18:46 UTC, albertmink approved these changes
LGTM

2024-04-05 10:57 UTC, merged