Small performance improvement in folder logic
abapGit/abapGit pull request #6941
Opened 2024-05-28 20:59 UTC by mbtools

For larger repositories, `zcl_abapgit_folder_logic` methods `path_to_package` or `package_to_path` are called many times with the same parameters. Once per package/path is sufficient but the calls are once per object/file.

This change introduces a local caching logic which should improve runtimes for serializing and deserializing repos.

For serializing the abapGit repo the improvement is about 0.2s (but I use 4 processes). With standalone (1 process) it will be more. For deserializing, I expect the improvement to be more noticeable since the logic requires more DB selections.

2024-06-02 10:05 UTC, larshp commented
perhaps split off the caching logic to a new local class? so its less intertangled with the actual logic

2024-06-06 05:06 UTC, larshp requested changes
see above

2024-06-08 13:06 UTC, mbtools commented
Refactored for minimal impact to existing class

2024-06-08 15:11 UTC, larshp approved these changes
nice

2024-06-08 19:01 UTC, merged