Added enhanced method resolution for background exit
abapGit/abapGit pull request #7059
Opened 2024-10-14 12:50 UTC by gardian12

Background user exit method resolution.
This implementation:
fixes #7057:
- missing error handling for dynamic method calls
- adding a warning message for not processed calls

enhanced:
- fully dynamic method determination based on ZIF_ABAPGIT_BACKGROUND interface
- new include for local ZIF_ABAPGIT_BACKGROUND implementations ZABAPGIT_BACKGROUND_USER_EXIT

2024-10-21 16:33 UTC, mbtools requested changes
The name of the standalone report is not fixed since you can keep various copies. Otherwise, looks good

2024-10-21 16:33 UTC, mbtools commented on src/background/zcl_abapgit_background.clas.abap
> +    IF sy-repid = c_name-report.
You can copy the standalone report for example to keep different versions.

Use this instead:

```abap
IF zcl_abapgit_factory=>get_environment( )->is_merged( ) = abap_true.
```

2024-10-21 16:33 UTC, mbtools commented on src/background/zcl_abapgit_background.clas.abap
> +          program = c_name-report
`sy-repid`

2024-10-21 16:33 UTC, mbtools commented on src/background/zcl_abapgit_background.clas.abap
> +        lv_classname = |\\PROGRAM={ c_name-report }\\CLASS={ <ls_local_class>-name }|.
`sy-repid`

2024-10-21 16:33 UTC, mbtools commented on src/background/zcl_abapgit_background.clas.abap
> +                 report    TYPE syrepid VALUE 'ZABAPGIT_STANDALONE',
not needed (see below)

2024-10-22 13:59 UTC, mbtools approved these changes
Looks good. Thanks!

2024-10-22 14:04 UTC, merged

2024-10-22 14:05 UTC, mbtools commented
Can you add something to https://docs.abapgit.org/user-guide/repo-settings/background-mode.html#custom-background-modes, please?

2024-10-22 20:19 UTC, gardian12 commented
Hello @mbtools, I've added [Pull Request](https://github.com/abapGit/docs.abapgit.org/pull/250) on doc.